name: .NET Core

on:
  push:
    branches:
    - master
    - feature/*
    - release/*
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test --no-build --configuration Release
    - name: Pack with dotnet
      run: dotnet pack --no-build --configuration Release