name: Nuke

on: [push, pullrequest]

jobs:
  macOS-latest:
    name: macOS-latest
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run './build.sh '
        run: ./build.sh 
